version: "3.9"

services:
  mongo:
    image: mongo:latest
    container_name: portal_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - portal_network

  redis:
    image: redis:alpine
    container_name: portal_redis
    ports:
      - "6379:6379"
    networks:
      - portal_network
  cassandra:
    image: cassandra:latest
    container_name: portal_cassandra
    ports:
      - "9042:9042"
    env_file:
      - .env
    volumes:
      - cassandra_data:/var/lib/cassandra
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "describe keyspaces"]
      interval: 15s
      timeout: 10s
      retries: 10
    networks:
      - portal_network

  #APLICACIONES
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: backend_dev
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
     # - /app/node_modules
    env_file:
      - .env
    command: npm run dev
    depends_on:
      mongo:
        condition: service_started
      redis:
        condition: service_started
      cassandra:
        condition: service_healthy
    networks:
      - portal_network
  frontend:
    build:
      context: ./front-end-news
      dockerfile: Dockerfile.dev
    container_name: frontend_dev
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports: 
      - "5173:5173"
    volumes:
      - ./front-end-news:/app
      - /app/node_modules
    env_file:
      - .env
    networks:
      - portal_network
volumes:
  mongo_data:
  cassandra_data:
networks:
  portal_network:
    driver: bridge
